# This workflow will do a clean install of Node dependencies, build the source code and run tests across different versions of Node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # (2022-12-03)
        # v16: Maintenance (end-of-life: 2023-09-11)
        # v18: LTS (end-of-life: 2025-04-30)
        # v19: Current (end-of-life: 2023-06-01)
        node-version: [16.x, 18.x, 19.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build packages
        run: lerna run build
      - name: Run tests
        run: npm test
